export default class Message {
  static CONTENT_TYPE_NOTIFICATION = "CONTENT_TYPE_NOTIFICATION";
  static CONTENT_TYPE_IMAGE = "CONTENT_TYPE_IMAGE";
  static CONTENT_TYPE_VIDEO = "CONTENT_TYPE_VIDEO";
  static CONTENT_TYPE_AUDIO = "CONTENT_TYPE_AUDIO";
  static CONTENT_TYPE_TEXT = "CONTENT_TYPE_TEXT";
}
