export default class Notification {
  static NOTIFICATION_MISS_CALL = "NOTIFICATION_MISS_CALL";
  static NOTIFICATION_INCOMING_CALL = "NOTIFICATION_INCOMING_CALL";
  static NOTIFICATION_GOING_CALL = "NOTIFICATION_GOING_CALL";
  static NOTIFICATION_DECLINE_CALL = "NOTIFICATION_DECLINE_CALL";
}
