# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    environment: development
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      DB_NAME: alo_rice_staging
      REGION: ap-southeast-1
      BUCKET_NAME: chat-app-alorice
      CLIENT_HOST: https://dev.alorice.xyz
      PORT: 5005
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: create env file
        run: |
          touch .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo USER_GMAIL=${{ secrets.USER_GMAIL }} >> .env
          echo PASS_GMAIL=${{ secrets.PASS_GMAIL }} >> .env
          echo SALT_ROUNDS=${{ secrets.SALT_ROUNDS }} >> .env
          echo MEDIA_HOST=${{ secrets.MEDIA_HOST }} >> .env
          echo DB_NAME=${{ env.DB_NAME }} >> .env
          echo BUCKET_NAME=${{ env.BUCKET_NAME }} >> .env
          echo CLIENT_HOST=${{ env.CLIENT_HOST }} >> .env
          echo PORT=${{ env.PORT }} >> .env
          cat .env
      - run: npm i
      - run: npm run test
      - run: npm run build --if-present
      - run: sudo cp -r dist/index.js node_modules /usr/share/nginx/alorice/staging/backend
      - run: sudo pm2 stop BackendAPI_Staging && sudo pm2 delete BackendAPI_Staging && sudo pm2 start --name=BackendAPI_Staging /usr/share/nginx/alorice/staging/backend/index.js
